### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by NextDozen** [deathtruth/SubnauticaMods-Deathtruth#1]
Can you tone down Reefback Leviathan sounds in grassy biomes? or mute them while we are in base?
Because it becomes annoying after some time plus if you make a base  in grassy biome it will certainly get on your nerves.
The sound just spams continuous. Thank you for your time I hope you make it work.

**Comment by deathtruth** [comment]
Hey, sure it's possible. I'll take a look at it this weekend.

**Comment by deathtruth** [comment]
Hey, I've added your feature request.

> - Added 2 new options in menu to control the indoor and outdoor volume of Reefback sounds
